stages:
  - hexo-build

hexo-build:
  stage: hexo-build
  script:
    - pwd
    - npm cache clean --force
    - npm install
    - cd themes/hexo-theme-sagiri/
    - npm cache clean --force
    - npm install
    - cd ../../
    - ./node_modules/hexo/bin/hexo clean
    - ./node_modules/hexo/bin/hexo generate
    - cp -r ./public /usr/blog
  only:
    - master
  tags:
    - hexo

