image: node:15.7.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install hexo-cli -g
  - npm install
  - test -e package.json && npm install
  - hexo generate

pages:
  script:
    - hexo generate
  artifacts:
    paths:
      - public
  # rules:
    # - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  only:
    - master
