stages:
  - install-module
  - hexo-build

install-module:
  stage: install-module
  script:
    - pwd
    - npm cache clean --force
    - npm install
    - cd themes/hexo-theme-sagiri/
    - npm cache clean --force
    - npm install
    - cd ../../
  only:
    - master
  tags:
    - hexo

hexo-build:
  stage: hexo-build
  script:
    - ./node_modules/hexo/bin/hexo clean
    - ./node_modules/hexo/bin/hexo generate
  only:
    - master
  tags:
    - hexo
