FROM node:15.7.0-alpine3.10

WORKDIR /usr/blog

RUN chmod 777 /usr/blog
# 切换中科大源
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
# 安装bash git openssh 以及c的编译工具
RUN apk add bash git openssh curl openrc

# 安装gitrunner
RUN curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
RUN chmod +x /usr/local/bin/gitlab-runner
RUN adduser -D -h /home/gitlab-runner -s /bin/sh gitlab
RUN gitlab-runner install --user=gitlab --working-directory=/home/gitlab-runner
RUN echo "#!/bin/sh" >> /start.sh
RUN echo "gitlab-runner stop" >> /start.sh
RUN echo "rm -rf /var/run/gitlab-runner.pid" >> /start.sh
RUN echo "gitlab-runner start" >> /start.sh
RUN chmod 777 /start.sh

# 因为频繁掉线所以让他一个小时重启一次
# RUN echo "0       */1     *       *       *       /bin/sh /start.sh" >> /etc/crontabs/root 

# 配置自启
ENTRYPOINT /start.sh && tail -f /dev/null

# 设置容器时区为上海，不然发布文章的时间是国际时间，也就是比我们晚8个小时
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& echo "Asia/Shanghai" > /etc/timezone \
&& apk del tzdata

# 升级npm
RUN npm install -g npm@8.12.1

# # 安装hexo
# RUN \ 
# npm config set registry https://registry.npm.taobao.org \
# && npm install \
# && npm install hexo-cli -g \
# && npm install hexo-server --save \
# && npm install hexo-asset-image --save \
# && npm install hexo-wordcount --save \
# && npm install hexo-generator-sitemap --save \
# && npm install hexo-generator-baidu-sitemap --save \
# && npm install hexo-deployer-git --save \
# && npm install hexo-renderer-swig --save \
# && npm install nprogress --save \
# && npm install hexo-tag-aplayer --save \
# && npm install zoom-image --save \
# && npm install disqusjs --save

CMD [ "/bin/sh"]
# EXPOSE 4000